---
title: "HW1"
author: "Genevieve Chiong and Kristin Gill"
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(janitor)
library(tidyverse)
library(lubridate)
library(scales)
```

```{r}
sf_climate <- read_csv(here("data", "2926351.csv")) %>% 
  clean_names()
```

```{r}
# consecutive hot days
source(here("R", "consecutive.R"))

tmax_filter <- sf_climate %>% 
  filter(date >= "1980-01-01" & date <= "2000-12-31") %>% 
  drop_na(tmax)

consecutive_days <- 1

temp_threshold <- 100

temp <- tmax_filter$tmax

consecutive_hot <- consecutive(data = temp, consecutive_days = consecutive_days, threshold = temp_threshold)
```

```{r}
# consecutive wet days
prcp_filter <- sf_climate %>% 
  filter(date >= "1938-04-01" & date <= "1958-12-31") %>% 
  drop_na(prcp)

consecutive_days <- 3

wet_threshold <- 1

prcp <- prcp_filter$prcp

#consecutive_wet <- consecutive(data = prcp, consecutive_days = consecutive_days, threshold = wet_threshold)
```


```{r}
# decadal temperature anomalies
sf_climate_new <- sf_climate %>% 
  mutate(year = year(date)) 

sf_climate_yearly <- sf_climate_new %>% 
  select(year, tmax) %>% 
  group_by(year) %>% 
  summarize(tmax = mean(tmax, na.rm = TRUE)) 

total_mean <- mean(sf_climate$tmax, na.rm = TRUE)

sf_climate_decade_new <- sf_climate_yearly %>% 
  filter(year >= 1930 & 2019 >= year) %>% 
  mutate(decade = case_when(year %in% c(1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939) ~ "1930", 
                            year %in% c(1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949) ~ "1940", 
                            year %in% c(1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959) ~ "1950", 
                            year %in% c(1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969) ~ "1960",
                            year %in% c(1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979) ~ "1970", 
                            year %in% c(1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989) ~ "1980", 
                            year %in% c(1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999) ~ "1990", 
                            year %in% c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009) ~ "2000", 
                            year %in% c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019) ~ "2010")) %>% 
  mutate(total_avg = 63.73) %>% 
  group_by(decade) %>% 
  summarize(tmax_avg = mean(tmax, na.rm = TRUE)) %>% 
  mutate(total_avg = 63.73) %>% 
  mutate(difference = (tmax_avg - total_avg)) 

  sf_climate_decade_new$decade <- as.numeric(sf_climate_decade_new$decade)

ggplot(data = sf_climate_decade_new, 
       aes(x = decade,
           y = difference)) + 
  geom_col(fill = "cadetblue4", color = "black") +
  ggtitle(label = "Decadal Temperature Anomalies, 1930-2020",
          subtitle = "San Francisco, CA") + 
  labs(x = "\nDecade",
       y = "\nDifference from Average (F)") + 
  scale_x_continuous(breaks = c(1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020, 2030)) + 
  scale_y_continuous(breaks = seq(-1.6, 2.4, by = 0.4), labels = comma) + 
  theme_bw() + 
  geom_smooth(method = "lm", 
              se = FALSE, 
              color = "gray30")

linear_regression = lm(difference ~ decade, data = sf_climate_decade_new)
summary(linear_regression)

```

```{r}
sf_climate_decade_new2 <- sf_climate_yearly %>% 
  filter(year >= 1930 & 2019 >= year) %>% 
  mutate(decade = case_when(year %in% c(1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939) ~ "1930", 
                            year %in% c(1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949) ~ "1940", 
                            year %in% c(1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959) ~ "1950", 
                            year %in% c(1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969) ~ "1960",
                            year %in% c(1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979) ~ "1970", 
                            year %in% c(1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989) ~ "1980", 
                            year %in% c(1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999) ~ "1990", 
                            year %in% c(2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009) ~ "2000", 
                            year %in% c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019) ~ "2010")) %>% 
  mutate(total_avg = 63.73) %>% 
  group_by(decade) %>% 
  summarize(tmax_avg = mean(tmax, na.rm = TRUE))

  sf_climate_decade_new2$decade <- as.numeric(sf_climate_decade_new2$decade)

ggplot(data = sf_climate_decade_new2, 
       aes(x = decade,
           y = tmax_avg)) + 
  geom_point() +
  ggtitle(label = "Decadal Temperature Anomalies, 1930-2020",
          subtitle = "San Francisco, CA") + 
  labs(x = "\nDecade",
       y = "\nDifference from Average (F)") + 
  theme_bw() + 
  geom_smooth(method = "lm")

linear_regression = lm(tmax_avg ~ decade, data = sf_climate_decade_new2)
summary(linear_regression)
```


```{r}
# Wilcoxon rank-sum test for 2 time chunks: 1930-1970; 1970-2010 

sf_climate_decade_new4 <- sf_climate_yearly %>% 
  filter(year >= 1930 & 2009 >= year)

t.test(subset(sf_climate_decade_new4$tmax, sf_climate_decade_new4$year %in% 1930:1950), subset(sf_climate_decade_new4$tmax, sf_climate_decade_new4$year %in% 1970:1990))

wilcox.test(subset(sf_climate_decade_new4$tmax, sf_climate_decade_new4$year %in% 1930:1950), subset(sf_climate_decade_new4$tmax, sf_climate_decade_new4$year %in% 1970:1990))
```

```{r}
# look at winter? 
sf_climate_new_season <- sf_climate_new %>% 
  mutate(month = month(date)) %>% 
  mutate(season = case_when(month %in% c(12, 1, 2) ~ "1", 
                            month %in% c(3, 4, 5) ~ "2",
                            month %in% c(6, 7, 8) ~ "3",
                            month %in% c(9, 10, 11) ~ "4"))

sf_clim_byseason <- sf_climate_new_season %>% 
  group_by(year, season) %>% 
  summarize(tmax = mean(tmax),
            tmin = mean(tmin), 
            precip = sum(prcp))

sf_clim_winter <- sf_clim_byseason %>% 
  filter(season == 1) 

ggplot(sf_clim_winter,
       aes(x = year,
           y = tmax)) + 
  stat_summary(fun.y = "mean",
               geom = "point",
               col = "cadetblue4", 
               size = 4) +
  theme_bw() +
  geom_smooth(method = "lm")


winter_regression = lm(tmax ~ year, data = sf_clim_winter) 
summary(winter_regression)

confint(winter_regression, "year", level = 0.95)

```


```{r}
# look at summer 
sf_climate_new_season <- sf_climate_new %>% 
  mutate(month = month(date)) %>% 
  mutate(season = case_when(month %in% c(12, 1, 2) ~ "1", 
                            month %in% c(3, 4, 5) ~ "2",
                            month %in% c(6, 7, 8) ~ "3",
                            month %in% c(9, 10, 11) ~ "4"))

sf_clim_byseason <- sf_climate_new_season %>% 
  group_by(year, season) %>% 
  summarize(tmax = mean(tmax),
            tmin = mean(tmin), 
            precip = sum(prcp))

sf_clim_summer <- sf_clim_byseason %>% 
  filter(season == 3) 

ggplot(sf_clim_summer,
       aes(x = year,
           y = tmax)) + 
  stat_summary(fun.y = "mean",
               geom = "point",
               col = "cadetblue4", 
               size = 4) +
  theme_bw() +
  geom_smooth(method = "lm")


summer_regression = lm(tmax ~ year, data = sf_clim_summer) 
summary(summer_regression)

confint(summer_regression, "year", level = 0.95)
```

```{r}
#tmax 
sf_climate_new = sf_climate %>% 
  mutate(year = year(date)) 

sf_climate_yearly = sf_climate_new %>% 
  select(year, tmax) %>% 
  group_by(year) %>% 
  summarize(tmax = mean(tmax)) 

ggplot(data = sf_climate_yearly,
       aes(x = year,
           y = tmax)) +
  geom_line()  
```




